group: travis_lts
#group: edge
#dist: trusty

env:
  global:
    TERM=dumb

language: java
jdk:
  - openjdk8
  - oraclejdk8

install: true
before_install:
  - sudo apt update
  - nvm install lts/*
  - npm i -g yarn
#  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
#  - stop_any 5432 5672 27017 8080

script:
  - bash gradlew clean build docs

  - export parent=$(pwd)

  - >
    for project in \
      plain-ts-toods \
      ts-2.3-null-and-undefined-types \
      ts-2.3-functional-oop \
    ; do

      cd ${parent}/${project}
      yarn -i
    done

cache:
  directories:
    - $HOME/.m2
    - $HOME/.yarn
    - $HOME/.gradle
